# Generated by Django 4.2.11 on 2024-03-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
